### ISSUE TITLE
NimbusExternalizerServiceでClassオブジェクトを非直列化できない

### ISSUE THREAD

**Issue by m-takata** [nimbus-org/nimbus#30]
以下のように実行すると、例外が発生する。
```
bsh % import jp.ossc.nimbus.service.io.*;
bsh % NimbusExternalizerService ext = new NimbusExternalizerService();
bsh % ext.create();
bsh % ext.start();
bsh % import java.io.*;
bsh % ByteArrayOutputStream baos = new ByteArrayOutputStream();
bsh % ext.writeExternal(String.class, baos);
bsh % ByteArrayInputStream bais = new ByteArrayInputStream(baos.toByteArray());
bsh % print(ext.readExternal(bais));

java.lang.IllegalAccessError: java.lang.Class
        at sun.reflect.GeneratedSerializationConstructorAccessor4.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at jp.ossc.nimbus.service.io.NimbusExternalizerService$MetaClass.newInstance(NimbusExternalizerService.java:1081)
        at jp.ossc.nimbus.service.io.NimbusExternalizerService$NimbusObjectInputStream.readObjectOverride(NimbusExternalizerService.java:522)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:421)
        at jp.ossc.nimbus.service.io.SerializableExternalizerService.readInternal(SerializableExternalizerService.java:490)
        at jp.ossc.nimbus.service.io.SerializableExternalizerService.readExternal(SerializableExternalizerService.java:428)
        at jp.ossc.nimbus.service.io.SerializableExternalizerService.readExternal(SerializableExternalizerService.java:404)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at bsh.Reflect.invokeMethod(Unknown Source)
        at bsh.Reflect.invokeObjectMethod(Unknown Source)
        at bsh.Name.invokeMethod(Unknown Source)
        at bsh.BSHMethodInvocation.eval(Unknown Source)
        at bsh.BSHPrimaryExpression.eval(Unknown Source)
        at bsh.BSHPrimaryExpression.eval(Unknown Source)
        at bsh.BSHArguments.getArguments(Unknown Source)
        at bsh.BSHMethodInvocation.eval(Unknown Source)
        at bsh.BSHPrimaryExpression.eval(Unknown Source)
        at bsh.BSHPrimaryExpression.eval(Unknown Source)
        at bsh.Interpreter.run(Unknown Source)
        at bsh.Interpreter.main(Unknown Source)
```

**Comment by m-takata** [comment]
pull requestをマージしたので、クローズ。
