### ISSUE TITLE
GaugeWriterServiceをマルチスレッドで使用すると、例外が発生する場合がある。

### ISSUE THREAD

**Issue by m-takata** [nimbus-org/nimbus#780]
java.lang.IllegalArgumentException: Collector already registered that provides name: performance_record_count                                                 at io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:54) 
at io.prometheus.client.SimpleCollector$Builder.register(SimpleCollector.java:259) 
at io.prometheus.client.SimpleCollector$Builder.register(SimpleCollector.java:251) 
at jp.ossc.nimbus.service.writer.prometheus.GaugeWriterService.write(GaugeWriterService.java:226)

**Comment by m-takata** [comment]
修正しました。
